name = "LANIMFE"
uuid = "4bdddc90-020a-4e59-bfa3-524b87b37479"
repo = "https://github.com/LANIMFE/LANIMFE-Registry"
description = "Julia packages registry from LANIMFE"

[packages]
4a901fcc-f81f-59f3-9077-2f09e0dff85c = { name = "ApproximationGrids", path = "A/ApproximationGrids" }
